use_frameworks!

platform :ios, '9.0'

target 'FakeSdkBle_Example' do
  pod 'FakeSdkBle', :path => '../'

  target 'FakeSdkBle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
